#baseurl = "http://localhost:81"
baseurl = "https://joaobi.github.io/blog/"
languageCode = "en-us"
title = "Joao Bilhim's (JB) blog"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
#disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command
#hemesDir = "../.."

[params]
    site_author = "Joao Bilhim (JB)"
    site_description = "The awesome blog of John Doe."
    location = "Occasionaly in Singapore, often somewhere else..."
    # Link custom assets relative to /static
    avatar = "img/joaobi-avatar.png"
    header_background = "img/lights.png"
    header_title = "Curiosity sparks growth"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "joaobi"
    facebook  = ""
    linkedin  = "joaobi"
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "joaobi"
    gplus     = ""
